name: Scheduled Job

on:
  schedule:
    - cron: "0 0 * * *" # Jeden Tag um 10:45 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "Hallo! Dies ist ein geplanter Cron-Job."

