name: Cron Job

on:
  schedule:
    - - cron: "*/2 * * * *"  # Dies ist die Cron-Syntax (z.B. jede Stunde)
  workflow_dispatch:  # Optional: Ermöglicht das manuelle Auslösen des Workflows

jobs:
  run-cronjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Führe Cronjob aus
        run: |
          echo "Cronjob läuft!"
          # Hier kannst du das Skript oder den Befehl einfügen, der ausgeführt werden soll

